-- Preserve customer contact details and assign readable order numbers.
-- Run in Supabase SQL Editor before deploying the storefront/admin updates.

alter table public.orders
  add column if not exists customer_email text;

alter table public.orders
  add column if not exists order_number bigint generated by default as identity;

update public.orders
set order_number = nextval(pg_get_serial_sequence('public.orders', 'order_number'))
where order_number is null;

update public.orders as orders
set customer_email = users.email
from auth.users as users
where orders.user_id = users.id
  and orders.customer_email is null;

create unique index if not exists orders_order_number_key
  on public.orders (order_number);

notify pgrst, 'reload schema';